INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.174:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:api:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 939, in ensure_sync
    return self.async_to_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 960, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [01/Jun/2024 16:16:44] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.174:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:api:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 939, in ensure_sync
    return self.async_to_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 960, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [01/Jun/2024 16:17:32] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.174:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:api:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 939, in ensure_sync
    return self.async_to_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 960, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [01/Jun/2024 16:18:52] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.174:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:api:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 939, in ensure_sync
    return self.async_to_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 960, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [01/Jun/2024 16:19:46] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.174:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:api:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 939, in ensure_sync
    return self.async_to_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roshan.sathwane\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 960, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
INFO:werkzeug:127.0.0.1 - - [01/Jun/2024 16:21:15] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
